# app/domain/auth_ports.py
# ============================================================================
# MCP Control Store Port
#
# Persistence contract for OAuth, throttling, and sanitized audit state.
# ============================================================================

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from app.domain.auth import (
    AuthorizationCode,
    AuthorizationRequest,
    OAuthClient,
    OAuthToken,
    ServicePrincipal,
    TokenFamily,
)


class ControlStorePort(Protocol):
    async def ensure_principal(self, login: str, display_name: str) -> ServicePrincipal: ...
    async def get_active_principal(self, login: str) -> ServicePrincipal | None: ...
    async def create_client(self, client: OAuthClient) -> OAuthClient | None: ...
    async def get_client(self, client_id: str) -> OAuthClient | None: ...
    async def create_request(
        self, request: AuthorizationRequest
    ) -> AuthorizationRequest | None: ...
    async def get_request(self, request_hash: str) -> AuthorizationRequest | None: ...
    async def consume_request(self, request_hash: str) -> bool: ...
    async def create_code(self, code: AuthorizationCode) -> AuthorizationCode | None: ...
    async def consume_code(
        self, code_hash: str, principal_id: str, client_id: str
    ) -> AuthorizationCode | None: ...
    async def create_family(self, family: TokenFamily) -> TokenFamily | None: ...
    async def create_token(self, token: OAuthToken) -> bool: ...
    async def get_token(self, hashed_token: str) -> OAuthToken | None: ...
    async def rotate_refresh_token(self, hashed_token: str, new_token: OAuthToken) -> bool: ...
    async def revoke_token(self, hashed_token: str, reason: str, revoked_by: str) -> bool: ...
    async def revoke_family(self, family_id: str, reason: str, revoked_by: str) -> bool: ...
    async def record_attempt(self, ip_hash: str, action: str, success: bool) -> bool: ...
    async def count_failures_since(self, ip_hash: str, action: str, since: datetime) -> int: ...
    async def append_audit(self, payload: dict[str, Any]) -> bool: ...
    async def cleanup(
        self, *, now: datetime, audit_before: datetime, attempts_before: datetime
    ) -> int: ...
